---
repos:
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.11
