-- fix-codeblock-tables.lua
-- AI: File generated by Cursor
-- Ensures code blocks with table-like content maintain proper indentation
--
-- When pandoc converts DocBook to markdown, it sometimes outputs lines starting
-- with `|` without proper indentation in code blocks. This happens because `|`
-- is the markdown pipe table delimiter, and pandoc tries not to interfere with it.
-- This filter fixes the indentation at the AST level before markdown generation.

function CodeBlock(elem)
    local text = elem.text
    local lines = {}

    -- Split into lines
    for line in text:gmatch("([^\n]*)\n?") do
        if line ~= "" or #lines > 0 then
            table.insert(lines, line)
        end
    end

    -- Check if this looks like a table (has lines with +- borders and | rows)
    local has_table_rows = false
    local has_border = false

    for _, line in ipairs(lines) do
        -- Check for table rows (lines starting with | after optional whitespace)
        if line:match("^%s*|") then
            has_table_rows = true
        end
        -- Check for table borders (lines with +- pattern)
        if line:match("^%s*%+%-") then
            has_border = true
        end
    end

    -- If it's a table-like block, normalize all indentation
    if has_table_rows and has_border then
        -- Find the indentation of border lines (they should have correct indentation)
        local border_indent = ""
        for _, line in ipairs(lines) do
            local indent = line:match("^(%s*)%+%-")
            if indent then
                border_indent = indent
                break
            end
        end

        -- Apply same indentation to all table-related lines
        local fixed_lines = {}
        for _, line in ipairs(lines) do
            local stripped = line:match("^%s*(.*)$")

            -- Check if this is a table-related line
            local is_table_line = stripped:match("^[|+]") or
                                  stripped == "..." or
                                  stripped == "…"

            if is_table_line then
                -- Check current indentation
                local current_indent = line:match("^(%s*)")

                -- Only fix if indentation is significantly less than border indent
                if #current_indent < #border_indent - 2 then
                    table.insert(fixed_lines, border_indent .. stripped)
                else
                    table.insert(fixed_lines, line)
                end
            else
                -- Not a table line, keep as-is
                table.insert(fixed_lines, line)
            end
        end

        elem.text = table.concat(fixed_lines, "\n")
    end

    return elem
end

return {{CodeBlock = CodeBlock}}



