#!/usr/bin/env python3
"""
AI: File generated by Cursor

Pandoc filter to improve DocBook to Markdown conversion:
1. Add book title from <info><title> as first H1
2. Convert <formalpara><title> (Div.formalpara-title) to headers at appropriate levels
"""

import sys
import json


def extract_string(inlines):
    """Extract plain text from inline elements"""
    if not inlines:
        return ""

    text = []
    for inline in inlines:
        if isinstance(inline, dict):
            if inline.get("t") == "Str":
                text.append(inline["c"])
            elif inline.get("t") == "Space":
                text.append(" ")
            elif inline.get("t") in ["Strong", "Emph", "Code"]:
                # Recursively extract from these
                if isinstance(inline.get("c"), str):
                    text.append(inline["c"])
                elif isinstance(inline.get("c"), list) and len(inline["c"]) > 1:
                    text.append(extract_string(inline["c"]))
            elif "c" in inline and isinstance(inline["c"], list):
                text.append(extract_string(inline["c"]))
    return "".join(text)


def unwrap_strong(inlines):
    """Remove Strong wrapper from inlines"""
    result = []
    for inline in inlines:
        if isinstance(inline, dict):
            if inline.get("t") == "Strong":
                # Extract content from Strong
                if isinstance(inline.get("c"), list):
                    result.extend(inline["c"])
                else:
                    result.append(inline)
            else:
                result.append(inline)
        else:
            result.append(inline)
    return result


def process_blocks(blocks):
    """Process a list of blocks, converting formalpara Divs to Headers"""
    new_blocks = []
    current_level = 0  # Track current section level

    for block in blocks:
        if not isinstance(block, dict):
            new_blocks.append(block)
            continue

        block_type = block.get("t")

        # Update current level when we see a Header
        if block_type == "Header":
            current_level = block["c"][0]  # First element is the level
            new_blocks.append(block)

        # Convert formalpara Div to Header
        elif block_type == "Div":
            attrs = block.get("c", [[], []])[0]  # [id, classes, key-value pairs]
            classes = attrs[1] if len(attrs) > 1 else []
            content = block.get("c", [[], []])[1]  # blocks inside the div

            if "formalpara-title" in classes and content:
                # This is a formalpara title - convert to header
                # The content should be a single Para with Strong
                first_block = content[0]
                if first_block.get("t") == "Para":
                    para_inlines = first_block.get("c", [])
                    # Remove Strong wrapper and create header
                    clean_inlines = unwrap_strong(para_inlines)
                    header_level = current_level + 1

                    header = {
                        "t": "Header",
                        "c": [header_level, ["", [], []], clean_inlines],
                    }
                    new_blocks.append(header)
                else:
                    # Unexpected structure, keep as-is
                    new_blocks.append(block)
            else:
                # Not a formalpara, keep as-is
                new_blocks.append(block)

        else:
            # Other block types, keep as-is
            new_blocks.append(block)

    return new_blocks


def extract_title_inlines(title_meta):
    """Convert title metadata to inline elements for header"""
    if isinstance(title_meta, dict) and title_meta.get("t") == "MetaInlines":
        return title_meta.get("c", [])
    return []


def main():
    # Read JSON from stdin
    doc = json.load(sys.stdin)

    # Extract book title from metadata
    book_title_inlines = None
    if "meta" in doc and "title" in doc["meta"]:
        title_meta = doc["meta"]["title"]
        book_title_inlines = extract_title_inlines(title_meta)

    # Process blocks
    if "blocks" in doc:
        doc["blocks"] = process_blocks(doc["blocks"])

        # Add book title as first H1
        if book_title_inlines:
            title_header = {"t": "Header", "c": [1, ["", [], []], book_title_inlines]}
            doc["blocks"].insert(0, title_header)

    # Write JSON to stdout
    json.dump(doc, sys.stdout)


if __name__ == "__main__":
    main()
