-- tightlists.lua
-- AI: File generated by Cursor
-- Convert top-level Para (and some BlockQuote cases from Google Docs) inside
-- list items into Plain, so pandoc will emit tight lists (no blank lines).
function compactifyItem(blocks)
  for i, blk in ipairs(blocks) do
    if blk.t == 'Para' then
      blocks[i] = pandoc.Plain(blk.content)
    elseif blk.t == 'BlockQuote' then
      -- Some converters (e.g. Google Docs -> docx) put bullets inside
      -- BlockQuote; unwrap the inner content if it's a single Para.
      local inner = blk.content[1]
      if inner and inner.t == 'Para' then
        blocks[i] = pandoc.Plain(inner.content)
      end
    end
  end
  return blocks
end

function compactifyList(list)
  -- list.content is a pandoc.List; use :map to apply to each item
  list.content = list.content:map(compactifyItem)
  return list
end

return {
  {
    BulletList = compactifyList,
    OrderedList = compactifyList
  }
}

