name: "Build and push rag-content-ogx container image"

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

  schedule:
    - cron: '45 02 * * *'

jobs:
  build-and-push-rag-content-ogx:
    uses: ./.github/workflows/_build-and-push-image.yaml
    secrets: inherit
    with:
      index_name_suffix: "-ogx"
      extra_build_args: "VECTOR_DB_TYPE=llamastack-faiss"
